/**
 * 
 */
package com.centris.util.SQLUtils;

/**
 * @author satish
 *
 */
public class AdvancedSalaryRequest {
	public static final String GET_EMPLOYEEDETAILS_BYID="select hm.EMPID,hm.bioid,hm.First_Name,hmp.ProjectRefCode,hpmp.ProjectCode from hrms_employee hm,hrms_project hmp,hrms_project_manager_mapping hpmp where hm.EMPID=? and hpmp.ManagerCode=?";
	public static final String GET_ACCERYEAR_CODE="select AccyearCode from hrms_accyear where AccadamicYear=?";
	public static final String SAVE_ADVANCED_SALARY_REQUEST="insert into hrms_employee_advance_salary(AdvSalCode,AccYearCode,Month,EMPID,ProjectCode,salary_amount,Comments,RequestedBy,requestedDate) values(?,?,?,?,?,?,?,?,?)";
	public static final String GET_ADVANCED_SALARY_REQUEST="select he.bioid,hs.requestedDate,hs.AdvSalCode,hs.EMPID,hs.ProjectCode,hs.Comments,hs.salary_amount,hs.RequestedBy,he.First_Name,hm.FirstName,hp.ProjectRefCode,hs.RequestedBy from hrms_employee_advance_salary hs,hrms_manager hm,hrms_employee he,hrms_project hp where hs.isDirectorApproved='Y' and hs.isAccountsApproved='N' and hs.EMPID=he.EMPID and hs.RequestedBy=hm.ManagerCode and hp.ProjectCode=hs.ProjectCode order by EMPID,hs.AdvSalCode";

	public static final String APPROVE_ADVANCE_SALARY_STATUS="update hrms_employee_advance_salary set isDirectorApproved=?,DirectorAppTime=?,DirecotorCode=?,ApprovedAmount=? where AdvSalCode=?";
	public static final String APPROVE_ADVANCE_SALARY_EMAIL_SEND="select he.First_Name,he.Official_Email_ID from hrms_employee he where he.EMPID in(select hm.EMPID from hrms_manager hm,hrms_employee_advance_salary hs where hs.AdvSalCode=? and hs.RequestedBy=hm.ManagerCode)";
	public static final String ADVANCE_SALARY_REQUEST_EMAIL_SEND="select he.Official_Email_ID,he.First_Name,hm.FirstName from hrms_director hd,hrms_manager_director_mapping hdm,hrms_manager hm, hrms_employee he where hd.DirectorCode=hdm.DirectorCode and hm.ManagerCode=hdm.ManagerCode and hm.ManagerCode=? and he.EMPID=hd.EMPID";
	public static final String GET_PROJECT_CODEREFERENCE_BY_MANAGER_CODE="select hm.ProjectRefCode from  hrms_project hm,hrms_project_manager_mapping hpm where hpm.ProjectCode=hm.ProjectCode and hpm.ManagerCode=?";
	public static final String GET_ADVANCED_SALARY_REQUEST_BY_DIRECTOR="select distinct hs.requestedDate,hs.AdvSalCode,he.bioid,hs.EMPID,hs.ProjectCode,hs.Comments,hs.salary_amount,hs.RequestedBy,he.First_Name,hm.FirstName,hp.ProjectRefCode,hs.RequestedBy from hrms_employee_advance_salary hs,hrms_manager hm,hrms_employee he,hrms_project hp,hrms_manager_director_mapping dm where hs.isDirectorApproved='N' and hs.EMPID=he.EMPID and hs.RequestedBy=hm.ManagerCode and hp.ProjectCode=hs.ProjectCode and hs.RequestedBy in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and dm.DirectorCode=? order by EMPID,hs.AdvSalCode";
	public static final String APPROVE_ADVANCE_SALARY_STATUS_BY_ADMIN="update hrms_employee_advance_salary set isAccountsApproved=?,AccountApprovedTime=?,AccountentCode=? where AdvSalCode=?";
	public static final String APPROVE_ADVANCE_SALARY_EMAIL_SEND_BY_ADMIN="select hm.email,hm.FirstName from hrms_manager hm,hrms_employee_advance_salary he where he.AdvSalCode=? and he.RequestedBy=hm.ManagerCode";
	
	
	public static final String APPROVE_ADVANCE_SALARY_STATUS_ADMIN ="update hrms_employee_advance_salary set isAccountsApproved=?,AccountApprovedTime=?,AccountentCode=?,ApprovedAmount=? where AdvSalCode=?";
	public static final String ADVANCE_SALARY_REQUEST_STATUS_EMAIL_SEND="select he.Official_Email_ID,he.First_Name from hrms_employee he,hrms_manager hm  where hm.ManagerCode=? and he.EMPID=hm.EMPID";
	public static final String ADVANCE_SALARY_CONSOLIDATED_REPORT="select a.ApprovedAmount,e.First_Name as employeename,e.bioid,a.RequestedBy,p.ProjectRefCode,a.Comments,case when DirectorAppTime='0000-00-00 00:00:00' then '-' else substr(a.DirectorAppTime,1,19) end approveddate,a.isDirectorApproved,m.FirstName as requestedbyname,a.AdvSalCode,a.salary_amount,a.ProjectCode,a.isAccountsApproved,a.AccountentCode,a.AccountApprovedTime,substr(a.requestedDate,1,19) as requestedDate from hrms_employee_advance_salary a left outer join hrms_project p on p.ProjectCode=a.ProjectCode left outer join hrms_manager m on m.ManagerCode=a.RequestedBy,hrms_director d,hrms_employee e where a.RequestedBy in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and d.DirectorCode=? and a.EMPID=e.EMPID and a.isDirectorApproved like ? and substr(a.requestedDate,1,19) >=? and substr(a.requestedDate,1,19)<=? order by length(a.RequestedBy),a.RequestedBy";
	public static final String ADVANCE_SALARY_CONSOLIDATED_REPORT_BY_PROJECT="select a.isDirectorApproved as dirctorStatus,a.isAccountsApproved as adminStatus,case a.ApprovedAmount when null then '-' else a.ApprovedAmount end ApprovedAmount,e.First_Name as employeename,e.bioid,a.RequestedBy,p.ProjectRefCode,a.Comments,case when DirectorAppTime='0000-00-00 00:00:00' then '-' else substr(a.DirectorAppTime,1,19) end approveddate,a.isDirectorApproved,m.FirstName as requestedbyname,a.AdvSalCode,a.salary_amount,a.ProjectCode,a.isAccountsApproved,a.AccountentCode,substr(a.requestedDate,1,19) as requestedDate,case when a.isAccountsApproved='Y' then (select First_Name from hrms_employee where EMPID in (select empId from hrms_user where userCode=a.AccountentCode)) else '-' end accountname from hrms_employee_advance_salary a left outer join hrms_project p on p.ProjectCode=a.ProjectCode left outer join hrms_manager m on m.ManagerCode=a.RequestedBy,hrms_director d,hrms_employee e where a.RequestedBy in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and d.DirectorCode=? and a.EMPID=e.EMPID and a.isDirectorApproved like ? and substr(a.requestedDate,1,19) >=? and substr(a.requestedDate,1,19)<=? order by length(a.ProjectCode),a.ProjectCode ";
	
	public static final String ADVANCE_SALARY_CONSOLIDATED_REPORT_MANAGER="select a.isDirectorApproved as dirctorStatus,a.isAccountsApproved as adminStatus,case a.ApprovedAmount when null then '-' else a.ApprovedAmount end ApprovedAmount,e.First_Name as employeename,e.bioid,a.RequestedBy,p.ProjectRefCode,a.Comments,case when DirectorAppTime='0000-00-00 00:00:00' then '-' else substr(a.DirectorAppTime,1,19) end approveddate,a.isDirectorApproved,m.FirstName as requestedbyname,a.AdvSalCode,a.salary_amount,a.ProjectCode,a.isAccountsApproved,a.AccountentCode,substr(a.requestedDate,1,19) as requestedDate,case when a.isAccountsApproved='Y' then (select First_Name from hrms_employee where EMPID in (select empId from hrms_user where userCode=a.AccountentCode)) else '-' end accountname from hrms_employee_advance_salary a left outer join hrms_project p on p.ProjectCode=a.ProjectCode left outer join hrms_manager m on m.ManagerCode=a.RequestedBy,hrms_director d,hrms_employee e where a.RequestedBy in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and d.DirectorCode=? and a.EMPID=e.EMPID and a.isDirectorApproved like ? and substr(a.requestedDate,1,19) >=? and substr(a.requestedDate,1,19)<=? order by length(a.RequestedBy),a.RequestedBy ";	
	public static final String ADVANCE_SALARY_ADMIN_APPROVED="select RequestedBy,DirecotorCode from hrms_employee_advance_salary where AdvSalCode=?";
	public static final String GET_DIRECTOR_MAIL_DETAILS="select d.Username,e.First_Name from hrms_director d,hrms_employee e where d.EMPID=e.EMPID and d.DirectorCode=?";
	public static final String GET_MANAGER_MAIL_DETAILS="select m.Username,m.FirstName from hrms_manager m where m.ManagerCode=?";
	
	
}
