package com.centris.util.SQLUtils;

public class EmployeeDashboard {

	//Employee Dashboard created by swathi
	public static final String SEARCH_EMPLOYEE_UNDER_MANAGER = "select e.EMPID,e.First_Name,e.Mobile_Number,e.Official_Email_ID,e.Present_Address,d.designationName from hrms_employee e,hrms_designation d,hrms_employee_manager_mapping em where e.isActive='Y' and d.DesignationCode=e.DesignationCode   and em.EmployeeId=e.EMPID and em.ManagerId=? and e.First_Name like ?";
	public static final String All_EMPLOYEES_UNDER_MANAGER = "select e.EMPID,e.First_Name,e.Mobile_Number,e.Official_Email_ID,e.Present_Address,d.designationName from hrms_employee e,hrms_designation d,hrms_employee_manager_mapping em where e.isActive='Y' and d.DesignationCode=e.DesignationCode   and e.EMPID=em.EmployeeId and em.ManagerId=?";
	public static final String GET_DAILY_ALLOWANCES = "select sum(a.Amount) as amount ,m.FirstName as postedby,sum(case when a.isApprovedByAccounts='Y' then a.AccountApprovedAmount else 0 end) approvedAmount from hrms_employee_daily_allowance a left outer join hrms_project p on p.ProjectRefCode=a.ProjectRefCode left outer join hrms_manager m on m.ManagerCode = a.Posted_By where  Allowance_Date >=? and Allowance_Date<=? and EMPCODE=? order by Allowance_Date asc";
	public static final String GET_PERSONAL_DETAILS = "select distinct e.EMPID,e.First_Name,e.BaseLocation,e.Mobile_Number,e.Present_Address,e.DOB,e.DOJ,dept.DEPT_NAME,e.Permanent_Address,e.Voter_ID_No,e.BloodGroup,e.Personal_Email_ID,e.EmpType ,des.designationName from hrms_employee e left outer join hrms_employee_manager_mapping em on e.EMPID=em.EmployeeId left outer join hrms_department_mapping dm on em.ManagerId=dm.UserCode left outer join hrms_department dept on dm.DepartmentCode=dept.DEPT_ID,hrms_designation des where e.DesignationCode=des.DesignationCode and  e.EMPID=?";
	public static final String GET_NOT_APPROVED_LEAVES = "select NoofLeaves,substring(RequestedDate,1,10)as requestdate,ReasonForLeave from hrms_employee_leave_request where RequestedBy=? and RequestedTo=? AND LeaveStatus ='NOT APPROVED'";
	public static final String GET_LEAVE_STATUS = "select NoofLeaves,substr(RequestedDate,1,10)as requseteddate,LeaveStatus,TotalDaysAproved from hrms_employee_leave_request where RequestedBy=?";
	public static final String GET_ATTENDANCE_DETAILS = "select count(*)as workingdays,sum(case when Attedence_Status='Present' and isAproved='Y' and   isPosted='Y' then 1 else 0 end)totpresent ,sum(case when Attedence_Status='Absent' and isAproved='Y' and   isPosted='Y'  then 1 else 0 end) totabsent,sum(case when Attedence_Status='Leave' and isAproved='Y' and   isPosted='Y' then 1 else 0 end)totleave,sum(case when Attedence_Status='Holiday' and isAproved='Y' and   isPosted='Y' then 1 else 0 end)totholidays from hrms_employee_attendance where Attendence_Date>=? and Attendence_Date <=?  and EMPID=?";
	public static final String GET_ATTENDANCE_NOT_POSTED_BY_EMPLOYEE = "select (select max(PostedTime) from hrms_employee_attendance where  isPosted='Y')  PostedTime,max(Attendence_Date) endDate,min(Attendence_Date) startDate,count(Attendence_Date)as pendingdays  from  hrms_employee_attendance where  isPosted='N' and EMPID=? order by PostedTime desc";
	public static final String GET_MORE_DAILY_ALLOWANCES = "select a.Allowance_Date,a.Amount,a.isApprovedByAccounts,p.Project_Name,m.FirstName as postedby,a.No_Of_days_Month,a.DAType,a.Single_team_GH,a.AccountApprovedAmount,a.Remarks,c.ClientName,a.Project_Manager,a.isRejected from hrms_employee_daily_allowance a left outer join hrms_project p on p.ProjectRefCode=a.ProjectRefCode left outer join hrms_manager m on m.ManagerCode = a.Posted_By left outer join hrms_client c on c.ClientCode = a.ClientCode  where  Allowance_Date >=? and Allowance_Date<=? and EMPCODE=? order by Allowance_Date asc";
		//Employee dashBoard queries in manager module written by seshu start 

	public static final String EMPLOYEE_PERSONAL_dETAILS_IN_MANAGER="select distinct e.EMPID,e.First_Name,e.BaseLocation,e.Mobile_Number,e.Present_Address,e.DOB,e.DOJ,dept.DEPT_NAME,e.Permanent_Address,e.Voter_ID_No,e.BloodGroup,e.Personal_Email_ID,e.EmpType ,des.designationName,e.Employee_image,e.Official_Email_ID from hrms_employee e left outer join hrms_employee_manager_mapping em on e.EMPID=em.EmployeeId left outer join hrms_department_mapping dm on em.ManagerId=dm.UserCode left outer join hrms_department dept on dm.DepartmentCode=dept.DEPT_ID,hrms_designation des where e.DesignationCode=des.DesignationCode and  e.EMPID=?";
	public static final String EMPLOYEE_ATTENDANCE_DETAILS_IN_MANAGER="select count(*) as workingdays,sum(case when Attedence_Status='Present' and isAproved='Y' and isPosted='Y' then 1 else 0 end)totpresent ,sum(case when Attedence_Status='Absent' and isAproved='Y' and isPosted='Y' then 1 else 0 end) totabsent,sum(case when Attedence_Status='Leave' and isAproved='Y' and isPosted='Y' then 1 else 0 end)totleave,sum(case when Attedence_Status='Holiday' and isAproved='Y' and isPosted='Y' then 1 else 0 end)totholidays from hrms_employee_attendance where Attendence_Date>=? and Attendence_Date <=? and Attendence_Date<=now() and EMPID=?";
	public static final String MANAGER_NOT_APPROVED_DETAILS_ATTENDANC="select hea.EMPID,max(PostedTime) PostedTime,he.First_Name,max(Attendence_Date) endDate,min(Attendence_Date) startDate from  hrms_employee_attendance hea,hrms_employee he where hea.EMPID=he.EMPID and hea.isPosted='Y' and hea.isAproved='N' and hea.EMPID=?  order by PostedTime desc";
	public static final String MANAGER_NOT_APPROVED_LEAVES="select NoofLeaves,substring(RequestedDate,1,10)as requestdate,ReasonForLeave from hrms_employee_leave_request where RequestedBy=? and RequestedTo=? and LeaveStatus='NOT APPROVED'";
	public static final String GET_LAST_APRROVEDDATE="select max(ApprovedTime) approvedtime from  hrms_employee_attendance hea  where  hea.isPosted='Y' and hea.isAproved='Y' and hea.EMPID=?  order by ApprovedTime desc";
	public static final String GET_DAILY_ALLOWANCES_BY_MANAGER = "select a.Allowance_Date,a.Amount,a.isApprovedByAccounts,p.Project_Name,m.FirstName as postedby,a.isRejected from hrms_employee_daily_allowance a left outer join hrms_project p on p.ProjectRefCode=a.ProjectRefCode left outer join hrms_manager m on m.ManagerCode = a.Posted_By where  Allowance_Date >=? and Allowance_Date<=now() and EMPCODE=?  and  Posted_By=?  order by Allowance_Date asc";
	public static final String GET_MORE_DAILY_ALLOWANCES_BY_MANAGER = "select a.Allowance_Date,a.Amount,a.isApprovedByAccounts,p.Project_Name,m.FirstName as postedby,a.No_Of_days_Month,a.DAType,a.Single_team_GH,a.AccountApprovedAmount,a.Remarks,c.ClientName,a.Project_Manager,a.isRejected from hrms_employee_daily_allowance a left outer join hrms_project p on p.ProjectRefCode=a.ProjectRefCode left outer join hrms_manager m on m.ManagerCode = a.Posted_By left outer join hrms_client c on c.ClientCode = a.ClientCode  where  Allowance_Date >=? and Allowance_Date<=? and EMPCODE=? and Posted_By=? order by Allowance_Date asc";
	public static final String GET_CLIAMS_BY_MANAGER="select me.MEXP_CODE,me.year,me.month,me.Local_conveyance,me.Travel_expenses,me.Staff_welfare,me.Telephone_expenses,me.Purchases,me.other_work_expenses,me.Miscellaneous,me.Total_amount_claimed,me.Total_amount_approved,me.isManagerApproved,me.isDirectorApproved,me.isAccountApproved,me.Account_Balance_Amt from hrms_monthly_expense me where me.EMPID=? and year=? and month=?";
	public static final String GET_ADVANCESALARY_BY_MANAGER="select eas.AdvSalCode,ay.AccadamicYear,eas.Month,sum(eas.salary_amount) as postedamount,sum(case when eas.isAccountsApproved='Y' then eas.ApprovedAmount else 0 end) approvedAmount,substr(eas.requestedDate,1,19),p.Project_Name,case when eas.isDirectorApproved='Y' then 'Approved' else 'Not Approved' end status from hrms_employee_advance_salary eas,hrms_project p,hrms_accyear ay where eas.ProjectCode=p.ProjectCode and eas.AccYearCode=ay.AccyearCode and eas.EMPID=? and eas.AccYearCode in (select AccyearCode from hrms_accyear where AccadamicYear=?) and eas.Month=?";
	public static final String GET_ADVANCESALARY_COMPLETEDETAILS="select e.First_Name,eas.AdvSalCode,ay.AccadamicYear,eas.Month,p.Project_Name,eas.salary_amount,substr(eas.requestedDate,1,10) as requestDate,eas.Comments,case when eas.isDirectorApproved='Y' then 'Approved' else 'Not Approved' end status,eas.ApprovedAmount,substr(eas.DirectorAppTime,1,10) as approvedDate,(select e.First_Name from hrms_employee e,hrms_director d where e.EMPID=d.EMPID and d.DirectorCode = eas.DirecotorCode) as directorname,case when eas.isAccountsApproved='Y' then 'Approved' else 'Not Approved' end accountsStatus,(select e.First_Name from hrms_employee e,hrms_user u where e.EMPID=u.empId and u.userCode = eas.AccountentCode) as adminName,substr(eas.AccountApprovedTime,1,10) as accountApprovedDate from hrms_employee_advance_salary eas,hrms_employee e,hrms_project p,hrms_accyear ay where eas.EMPID=e.EMPID and eas.ProjectCode=p.ProjectCode and eas.AccYearCode=ay.AccyearCode and eas.EMPID like ? and eas.AccYearCode=? and eas.Month like ?";
	
	public static final String GET_EMPLOYEE_CLIAMES_VIEW="select me.year,me.month,case when me.ManagerCode is null then '-' else (select First_Name from hrms_employee where EMPID in (select EMPID from hrms_manager where ManagerCode=me.ManagerCode )) end managerName,me.Local_conveyance,me.Travel_expenses,me.Staff_welfare,me.Telephone_expenses,me.Purchases,me.other_work_expenses,me.Miscellaneous,me.Total_amount_claimed,case when me.Total_amount_approved is null then '-' else me.Total_amount_approved end approvedAmount,case when me.Advance_paid is null then '-' else me.Advance_paid end advancePaid,case when me.Balance is null then '-' else me.Balance end balance,me.isManagerApproved,substr(me.managerApprovedDate,1,10) as managerApprovedDate,me.isDirectorApproved,substr(me.directorApprovedDate,1,10) as directorApprovedDate,me.isAccountApproved,substr( me.accountApprovedDate,1,10 ) accountsApprovedDate,case when me.isDirectorApproved='N' then '-' else (select First_Name from hrms_employee where EMPID in (select EMPID from hrms_director where DirectorCode in (select DirectorCode from hrms_manager_director_mapping where ManagerCode=me.ManagerCode))) end approvedDirector,case when me.ApprovedAccountCode is null then '-' else (select First_Name from hrms_employee where EMPID in  (select EMPID from hrms_user where userCode=me.ApprovedAccountCode )) end approvedbyacnt,me.Account_Balance_Amt,me.Director_Balance_Amt from hrms_monthly_expense me where  EMPID=? and year in (select AccadamicYear from hrms_accyear where AccyearCode=?) and month like ?";

		//Employee dashBoard queries in manager module written by seshu end
	
	
	//For employee attendance View
	public static final String GET_EMPLOYEE_ATTENDANCE="select eatt.Attendence_Date,eatt.EMPID,eatt.Attedence_Status,eatt.intime,eatt.outtime,eatt.totaltime,eatt.Location,eatt.ASTCode,ast.StatusType,pjt.ClientName,emp.First_Name,eatt.isAproved,eatt.isPosted,eatt.ManagerCode from hrms_employee emp,hrms_employee_attendance eatt left outer join hrms_attendence_status_type ast on eatt.ASTCode=ast.ASTCode left outer join hrms_client pjt on eatt.ProjectCode=pjt.ClientCode where  eatt.EMPID=emp.EMPID and eatt.EMPID=? and eatt.Attendence_Date between ? and ? order by eatt.Attendence_Date";
	public static final String GET_MANAGER="select FirstName as name  from hrms_manager where ManagerCode=?";
	public static final String GET_DIRECTOR="select e.First_Name as name from hrms_employee e,hrms_director d where e.EMPID=d.EMPID and d.DirectorCode=?";
	
	public static final String GET_TRAVEL_ALLOWANCES = "select sum(a.Amount) as amount ,m.FirstName as postedby,sum(case when a.isApprovedByAccounts='Y' then a.AccountApprovedAmount else 0 end) approvedAmount from hrms_ticket_booking a left outer join hrms_manager m on m.ManagerCode = a.Posted_By where  Travelling_Date >=? and Travelling_Date<=? and resource_who_on_travel_empcode=? order by Travelling_Date asc";
	public static final String GET_EMPLOYEE_BY_EMPCODE = "select concat(First_Name,'-',bioid) AS EMPNAME from hrms_employee where EMPID=?";
	public static final String GET_ADMIN_NAME = "select concat(e.First_Name,'-',e.bioid) AS EMPNAME from hrms_employee e,hrms_user u  where u.empId=e.EMPID and  u.userCode=?";
	
	public static final String GET_TRAVEL_ALLOWANCES_BY_MANAGER_AND_EMP = "select t.Posted_Date,t.Booked_date,t.Travelling_Date,t.Traveling_From,t.Traveling_To,t.Amount,t.ApprovedAmount,t.Tkt_Booked_by_empcode,t.resource_who_on_travel_empcode,t.Debit_crdit_card_usedBy_empcode,t.ApprovedAccountsCode,substr(t.AccountsApprovedTime,1,19) as approvedtime,t.isApprovedByAccounts,t.ProjectRefCode,t.Project_Manager,p.Project_Name,m.FirstName,c.ClientName,t.mode  from  hrms_ticket_booking t   left outer join hrms_manager m  on  m.ManagerCode=t.Posted_By left outer join  hrms_project p on p.ProjectCode=t.ProjectCode left outer join hrms_client c on t.ClientCode=c.ClientCode   where   substr(t.Posted_Date,1,10) >=? and   substr(t.Posted_Date,1,10)<=? and t.resource_who_on_travel_empcode=? and Posted_By=? order by Travelling_Date,Posted_Date desc";
	
	public static final String GET_EMPLOYEE_CLIAMES_VIEW_IN_MANAGER = " select me.year,me.month,case when me.ManagerCode is null then '-' else (select First_Name from hrms_employee where EMPID in (select EMPID from hrms_manager where ManagerCode=me.ManagerCode )) end managerName,me.Local_conveyance,me.Travel_expenses,me.Staff_welfare,me.Telephone_expenses,me.Purchases,me.other_work_expenses,me.Miscellaneous,me.Total_amount_claimed,case when me.Total_amount_approved is null then '-' else me.Total_amount_approved end approvedAmount,case when me.Advance_paid is null then '-' else me.Advance_paid end advancePaid,case when me.Balance is null then '-' else me.Balance end balance,me.isManagerApproved,substr(me.managerApprovedDate,1,10) as managerApprovedDate,me.isDirectorApproved,substr(me.directorApprovedDate,1,10) as directorApprovedDate,me.isAccountApproved,substr( me.accountApprovedDate,1,10 ) accountsApprovedDate,case when me.isDirectorApproved='N' then '-' else (select First_Name from hrms_employee where EMPID in (select EMPID from hrms_director where DirectorCode in (select DirectorCode from hrms_manager_director_mapping where ManagerCode=me.ManagerCode))) end approvedDirector,case when me.ApprovedAccountCode is null then '-' else (select First_Name from hrms_employee where EMPID in  (select EMPID from hrms_user where userCode=me.ApprovedAccountCode )) end approvedbyacnt,me.Account_Balance_Amt,me.Director_Balance_Amt from hrms_monthly_expense me where  EMPID=?  and year=? and month like ?";


	public static final String GET_TRAVEL__MORE_ALLOWANCES = "select t.Posted_Date,t.Booked_date,t.Travelling_Date,t.Traveling_From,t.Traveling_To,t.Amount,t.ApprovedAmount,t.Tkt_Booked_by_empcode,t.resource_who_on_travel_empcode,t.Debit_crdit_card_usedBy_empcode,t.ApprovedAccountsCode,substr(t.AccountsApprovedTime,1,19) as approvedtime,t.isApprovedByAccounts,t.ProjectRefCode,t.Project_Manager,p.Project_Name,m.FirstName,c.ClientName,t.mode  from  hrms_ticket_booking t   left outer join hrms_manager m  on  m.ManagerCode=t.Posted_By left outer join  hrms_project p on p.ProjectCode=t.ProjectCode left outer join hrms_client c on t.ClientCode=c.ClientCode   where   substr(t.Posted_Date,1,10) >=? and   substr(t.Posted_Date,1,10)<=? and t.resource_who_on_travel_empcode=?";


}
