package com.centris.util.SQLUtils;

public class LogReportSqlUtil {
	
	//public static final String GET_ALL_MANAGERS_BY_DEPT="select hm.FirstName,hm.ManagerCode from hrms_manager hm,hrms_department_mapping hmd where hmd.UserCode=hm.ManagerCode and hmd.DepartmentCode=?";
	public static final String GET_MANAGER_BY_DEPARTMENT_CODE="SELECT hm.FirstName,hm.ManagerCode from hrms_manager hm,hrms_department_mapping hmd where hmd.UserCode=hm.ManagerCode and hmd.DepartmentCode=?";
	public static final String GET_MANAGER_BY_DEPARTMENT_CODE_DIRECTOR="SELECT distinct hm.FirstName,hm.ManagerCode from hrms_manager hm,hrms_department_mapping hmd,hrms_manager_director_mapping dm where hmd.UserCode=hm.ManagerCode and hmd.DepartmentCode=? and  hm.ManagerCode in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=?)";
	public static final String GET_ALL_EMPLOYEES="select e.EMPID,e.First_Name from hrms_employee e,hrms_employee_manager_mapping em where em.EmployeeId=e.EMPID and em.ManagerId=? ";
//	public static final String GET_LOG_REPORT="select * from  (select * from ( select DATE_ADD(?, INTERVAL ROW DAY) as Date from ( SELECT @row := @row + 1 as row FROM (select 0 union all select 1 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8) t1, (select 0 union all select 1 union all select 3 union all select 4 union all select 5 union all select 6  union all select 7 union all select 8) t2, (select 0 union all select 1 union all select 3 union all select 4 union all select 5 union all select 6  union all select 7 union all select 8) t4, (SELECT @row:=-1) t3 limit ? ) b) c, (select First_Name,bioid,EMPID from hrms_employee  where  EMPID like ? ) f) empDetails left outer join (select AI_EMP_ID,AI_BIO_ID,AI_EMP_DATE,group_concat(AI_EMP_TIME) AI_EMP_TIME from hrms_att_log_details where AI_EMP_DATE between ? and ? group by AI_EMP_DATE ) ld  on  ld.AI_EMP_DATE=empDetails.Date and ld.AI_EMP_ID=empDetails.bioid order by AI_EMP_ID,Date,AI_EMP_TIME";
	public static final String GET_LOG_REPORT="select * from  (select * from ( select DATE_ADD(?, INTERVAL ROW DAY) as Date from ( SELECT @row := @row + 1 as row FROM (select 0 union all select 1 union all select 3 union all select 4 union all select 5 union all select 6 union all select 7 union all select 8) t1, (select 0 union all select 1 union all select 3 union all select 4 union all select 5 union all select 6  union all select 7 union all select 8) t2, (select 0 union all select 1 union all select 3 union all select 4 union all select 5 union all select 6  union all select 7 union all select 8) t4, (SELECT @row:=-1) t3 limit ? ) b) c, (select First_Name,bioid,EMPID from hrms_employee  where  EMPID like ? ) f) empDetails left outer join (select AI_EMP_ID,AI_BIO_ID,AI_EMP_DATE,group_concat(AI_EMP_TIME) AI_EMP_TIME from hrms_att_log_details where AI_EMP_DATE between ? and ? and AI_EMP_ID in (select bioid from hrms_employee  where  EMPID like ?) group by AI_EMP_DATE ) ld  on  ld.AI_EMP_ID=empDetails.bioid and ld.AI_EMP_DATE=empDetails.Date order by Date,AI_EMP_ID";

}
