package com.centris.util.SQLUtils;

public class AllowancesClaimByManagerSqlUtil {
	
	
	//Allowances Approved by admin
	
	public static final String GET_ALLOWANCES_NOT_APPROVED="select eda.ApprovedAmount,eda.DirectorRemarks, eda.EMPCODE,eda.DALCode,e.bioid as BioCode,e.First_Name as employeename,eda.Location,eda.Amount,eda.Project_Manager,eda.ProjectRefCode,eda.Team_Lead,eda.Remarks,eda.Allowance_Date,e.HDFC_AC,c.ClientName,m.FirstName as managername,eda.Posted_By,eda.No_Of_days_Month,eda.Single_team_GH,eda.DAType,eda.isApprovedByDirector from hrms_employee_daily_allowance eda,hrms_employee e,hrms_client c,hrms_manager m where eda.Posted_By in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=? ) and eda.EMPCODE=e.EMPID and eda.ClientCode=c.ClientCode and eda.Project_Manager=m.ManagerCode and eda.isConflict='N' and substr(eda.Posted_Date,1,10)>=? and substr(eda.Posted_Date,1,10)<=? order by eda.Posted_By";
	public static final String GET_SINGLE_ALLOWANCE="select eda.Posted_Date,m.FirstName as managername,DirectorApprovedTime,(select First_Name from hrms_employee e,hrms_director d where e.EMPID=d.EMPID and d.DirectorCode=eda.ApprovedDirectorCode ) as directorName,(select FirstName from hrms_manager where ManagerCode=eda.Project_Manager) as projectManager,c.ClientName,eda.Team_Lead,eda.Single_team_GH,eda.DAType,eda.No_Of_days_Month,eda.Location,e.HDFC_AC,(case when eda.Remarks='' then '' else eda.Remarks end) postedByRemarks,(case when  eda.DirectorRemarks='' then '-' else eda.DirectorRemarks end) directorRemarks from hrms_employee_daily_allowance eda,hrms_employee e,hrms_client c,hrms_manager m where eda.EMPCODE=e.EMPID and eda.ClientCode=c.ClientCode and eda.Posted_By=m.ManagerCode and eda.DALCode=?";
	public static final String APPROVE_SINGLE_ALLOWANCE="update hrms_employee_daily_allowance set ApprovedAmount=?,DirectorRemarks=?,isApprovedByDirector='Y',ApprovedDirectorCode=?,DirectorApprovedTime=? where DALCode=?";
	public static final String GET_CONFLICT_EMPLOYEES="select eda.ApprovedAmount,eda.DirectorRemarks, eda.EMPCODE,eda.DALCode,e.bioid as BioCode,e.First_Name as employeename,eda.Location,eda.Amount,eda.Project_Manager,eda.ProjectRefCode,eda.Team_Lead,eda.Remarks,eda.Allowance_Date,e.HDFC_AC,c.ClientName,m.FirstName as managername,eda.Posted_By,eda.No_Of_days_Month,eda.Single_team_GH,eda.DAType,eda.isApprovedByDirector from hrms_employee_daily_allowance eda,hrms_employee e,hrms_client c,hrms_manager m  where eda.Posted_By in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=? ) and eda.EMPCODE=e.EMPID and eda.ClientCode=c.ClientCode and eda.Project_Manager=m.ManagerCode and eda.isConflict='Y' and eda.Allowance_Date>=? and eda.Allowance_Date<=? order by eda.Posted_By";
	public static final String GET_MAIL_DETAILS="select eda.Posted_By,eda.Amount,e.First_Name,eda.ApprovedAmount,m.email,eda.Allowance_Date,hd.Username as directorMailID from hrms_employee_daily_allowance eda left outer join hrms_director hd on hd.DirectorCode=eda.ApprovedDirectorCode,hrms_employee e,hrms_manager m  where eda.EMPCODE=e.EMPID and eda.Posted_By=m.ManagerCode and eda.DALCode=?";
	public static final String GET_EMP_ALLOWANCES = "select a.BioCode,e.First_Name,a.ProjectRefCode,a.Amount,a.ApprovedAmount,a.Allowance_Date from hrms_employee_daily_allowance a,hrms_employee e where e.bioid=a.BioCode and a.DALCode=?";
	public static final String GET_EMP_ALLOWANCES_BY_ADMIN = "select a.BioCode,e.First_Name,a.ProjectRefCode,a.Amount,a.AccountApprovedAmount from hrms_employee_daily_allowance a,hrms_employee e where e.bioid=a.BioCode and a.DALCode=?";
	//Allowances Approved by admin
	
	public static final String GET_ALLOW_NOT_APPROVEBY_ADMIN="select eda.isApprovedByAccounts,(select e.First_Name from hrms_employee e,hrms_user u where e.EMPID=u.empId and u.userCode=eda.ApprovedAccountsCode) as approvedAccountantName,eda.AccountsApprovedTime,eda.isRejected,eda.isMailSent,eda.MailSentTime,eda.AccountApprovedAmount,eda.AccountsRemarks,AccountsRemarks,eda.isApprovedByAccounts,eda.ApprovedDirectorCode,eda.ApprovedAmount,eda.DirectorRemarks,d.EMPID as diectorId,e.First_Name as directorName,e.bioid,eda.EMPCODE,eda.DALCode,(select bioid from hrms_employee where EMPID=eda.EMPCODE) as BioCode,eda.Location,eda.Amount,eda.Project_Manager,eda.ProjectRefCode,eda.Team_Lead,eda.Remarks,eda.Allowance_Date,e.HDFC_AC,c.ClientName,m.FirstName as managername,eda.Posted_By,eda.No_Of_days_Month,eda.Single_team_GH,eda.DAType,eda.isApprovedByDirector from hrms_employee_daily_allowance eda,hrms_employee e,hrms_client c,hrms_manager m,hrms_director d where d.EMPID=e.EMPID and eda.ClientCode=c.ClientCode and eda.Project_Manager=m.ManagerCode and d.DirectorCode=eda.ApprovedDirectorCode and eda.isConflict='N' and eda.isApprovedByDirector='Y' and substr(eda.DirectorApprovedTime,1,10)>=? and substr(eda.DirectorApprovedTime,1,10)<=? order by length(eda.ApprovedDirectorCode),eda.ApprovedDirectorCode";
	public static final String GET_CONFLICTALLOW_NOT_APPROVEBY_ADMIN="select eda.isApprovedByAccounts,(select e.First_Name from hrms_employee e,hrms_user u where e.EMPID=u.empId and u.userCode=eda.ApprovedAccountsCode) as approvedAccountantName,eda.AccountsApprovedTime,eda.isRejected,eda.isMailSent,eda.MailSentTime,eda.AccountApprovedAmount,eda.AccountsRemarks,AccountsRemarks,eda.isApprovedByAccounts,eda.ApprovedDirectorCode,eda.ApprovedAmount,eda.DirectorRemarks,d.EMPID as diectorId,e.First_Name as directorName,e.bioid,eda.EMPCODE,eda.DALCode,(select bioid from hrms_employee where EMPID=eda.EMPCODE)as BioCode,eda.Location,eda.Amount,eda.Project_Manager,eda.ProjectRefCode,eda.Team_Lead,eda.Remarks,eda.Allowance_Date,e.HDFC_AC,c.ClientName,m.FirstName as managername,eda.Posted_By,eda.No_Of_days_Month,eda.Single_team_GH,eda.DAType,eda.isApprovedByDirector from hrms_employee_daily_allowance eda,hrms_employee e,hrms_client c,hrms_manager m,hrms_director d where d.EMPID=e.EMPID and eda.ClientCode=c.ClientCode and eda.Project_Manager=m.ManagerCode and d.DirectorCode=eda.ApprovedDirectorCode and eda.isConflict='Y' and eda.isApprovedByDirector='Y' and eda.Allowance_Date>=? and eda.Allowance_Date<=? order by length(eda.ApprovedDirectorCode),eda.ApprovedDirectorCode";
	public static final String APPROVE_ALLOWANCE_BY_ADMIN="update hrms_employee_daily_allowance set isApprovedByAccounts='Y',ApprovedAccountsCode=?,AccountsApprovedTime=?,AccountsRemarks=?,AccountApprovedAmount=? where DALCode=?";
	public static final String GET_ALL_MAIL_IDS="select d.Username,m.email from  hrms_employee_daily_allowance eda,hrms_manager m,hrms_director d where d.DirectorCode=eda.ApprovedDirectorCode and  m.ManagerCode=eda.Posted_By and DALCode=?";
	public static final String UPDATE_REJET_ALLOWANCE_DETAILS="update hrms_employee_daily_allowance set isRejected='Y',AccountsRemarks=?,AccountsApprovedTime=?,ApprovedAccountsCode=?,AccountApprovedAmount=? where DALCode=?";
	public static final String UPDATE_MAILSTATUS="update hrms_employee_daily_allowance set isMailSent='Y',MailSentTime=? where DALCode=?";
	
	//Employee Allowances Claim by Manager
	public static final String CHECK_BIOID = "select count(da.BioCode),da.Amount,e.EMPID,e.First_Name,e.HDFC_AC,da.No_Of_days_Month,da.Single_team_GH,da.DAType,da.Project_Manager,da.ClientCode,da.ProjectRefCode,da.Team_Lead,da.Location,da.Remarks,da.Posted_By,da.ProjectCode from hrms_employee_daily_allowance da ,hrms_employee e where  da.EMPCODE=e.EMPID and   isConflict='N' and  da.BioCode=? and da.Allowance_Date=?  group by BioCode";
	public static final String GET_EMPLOYEE_DETAILS_BY_BIOID = "select e.EMPID,e.First_Name as empname,e.HDFC_AC,m.ManagerCode,m.FirstName as managername from hrms_employee e  left outer join hrms_employee_manager_mapping emm on e.EMPID=emm.EmployeeId  left outer join hrms_manager m on emm.ManagerId=m.ManagerCode where  e.bioid=?";
	public static final String SAVE_DAILY_ALLOWANCES = "insert into hrms_employee_daily_allowance(DALCode,BioCode,EMPCODE,Amount,No_Of_days_Month,Single_team_GH,DAType,Project_Manager,ClientCode,ProjectCode,ProjectRefCode,Team_Lead,Location,Remarks,Allowance_Date,Posted_Date,Posted_By,isConflict)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,now(),?,?)";
	public static final String GET_POSTED_MANAGER = "select e.First_Name,e.bioid from hrms_manager m,hrms_employee e where e.EMPID=m.EMPID and  m.ManagerCode=? and e.isActive='Y'";
	public static final String SEARCH_BIOID_TERM = "select concat(e.First_Name,'-',e.bioid)as BioId from hrms_employee e where  e.EMPID NOT IN(select d.EMPID from hrms_director d where d.isActive='Y')  and e.isActive='Y' and  First_Name like ?";
	public static final String GET_CLIENT_BY_PROJECT = "  select ClientName from hrms_project where ProjectRefCode=?";
	public static final String GET_CLAIMED_ALLOWANCES_BY_MANAGER_COUNT = "select count(*) from hrms_employee_daily_allowance where  Posted_By=?  and Allowance_Date=?";
	public static final String GET_CLIMED_ALOOWANCES_BY_MANAGER = "select da.BioCode,da.EMPCODE,e.First_Name,da.Amount,da.No_Of_days_Month,da.Single_team_GH,DAType,da.ProjectRefCode,da.Team_Lead,da.Location,da.Remarks,da.Allowance_Date,substr(Posted_Date,1,19)as posteddate,m.FirstName as projectmanager,c.ClientName from hrms_employee_daily_allowance da left outer join hrms_employee e on da.EMPCODE=e.EMPID left outer join hrms_manager m on da.Project_Manager=m.ManagerCode left outer join hrms_client c on da.ClientCode=c.ClientCode where  Posted_By=? and  Allowance_Date=?";
	public static final String GET_EMPLOYEE_BY_EMPCODE = "select First_Name,HDFC_AC,bioid from hrms_employee where EMPID=? and isActive='Y'";
	public static final String GET_MANAGER_BY_MGRCODE = "select e.First_Name from hrms_manager m,hrms_employee e where e.EMPID=m.EMPID and  m.ManagerCode=? and e.isActive='Y'";
	public static final String GET_POSTED_BY_MANAGER = "select FirstName from hrms_manager where ManagerCode=?";

	
	public static final String REJECT_ALLOWANCES_BYDIRECTOR = "update hrms_employee_daily_allowance set isApprovedByDirector='R',DirectorRemarks=?,DirectorApprovedTime=?,ApprovedDirectorCode=?,ApprovedAmount=? where DALCode=?";
	
	public static final String GET_MGRMAIL_FORALL_APPROVE = "select m.email from  hrms_employee_daily_allowance eda,hrms_manager m where m.ManagerCode=eda.Posted_By and DALCode=?";

	public static final String GET_EMPLOYEE_DETAILS_FORM_ALLOWANCES = "select e.EMPID,e.First_Name,e.HDFC_AC,da.Project_Manager,da.ClientCode,da.ProjectRefCode,da.Team_Lead,da.Location,da.Remarks,da.Posted_By,da.ProjectCode from hrms_employee_daily_allowance da ,hrms_employee e where  da.EMPCODE=e.EMPID and  da.BioCode=? order by da.Allowance_Date desc limit 1 ";
	public static final String GET_DIRECTOR_MAILID = "select d.Username,e.First_Name from hrms_director d,hrms_manager_director_mapping dm,hrms_employee e where dm.DirectorCode=d.DirectorCode and d.EMPID=e.EMPID and  d.isActive='Y' and dm.ManagerCode=?";
	public static final String GET_EMP_FIRSTNAME = "select First_Name from hrms_employee where EMPID=?";
	public static final String GET_MORE_DAILY_ALLOWANCES_BY_MANAGER = "select concat(e.First_Name,'-',e.bioid) as empname,a.Allowance_Date,a.Amount,a.isApprovedByAccounts,p.ProjectRefCode,m.FirstName as postedby,a.No_Of_days_Month,a.DAType,a.Single_team_GH,a.AccountApprovedAmount,a.Remarks,c.ClientName,a.Project_Manager,a.isRejected from hrms_employee_daily_allowance a left outer join hrms_project p on p.ProjectRefCode=a.ProjectRefCode left outer join hrms_manager m on m.ManagerCode = a.Posted_By left outer join hrms_client c on c.ClientCode = a.ClientCode left outer join hrms_employee e on e.EMPID = a.EMPCODE where  Allowance_Date >=? and Allowance_Date<=? and Posted_By=? order by Allowance_Date desc";

	
	
	
	//For consolidated information manager wise in director module
	public static final String GET_MAXMIN_DATES_FOR_MANAGER = "select sum(Amount) as amount,max(Allowance_Date) as maxdate,min(Allowance_Date) as mindate from hrms_employee_daily_allowance where Posted_By=? and isConflict='N' and substr(Posted_Date,1,10)>=? and substr(Posted_Date,1,10)<=?";
	
	
	public static final String GET_MAXMIN_DATES_FOR_DIRECTOR ="select sum(ApprovedAmount) as amount,max(Allowance_Date) as maxdate,min(Allowance_Date) as mindate from hrms_employee_daily_allowance where ApprovedDirectorCode=? and isConflict='N' and substr(DirectorApprovedTime,1,10)>=? and substr(DirectorApprovedTime,1,10)<=?";

	public static final String GET_MANG_EMP_ALLOWANCES = "select a.BioCode,e.First_Name,a.ProjectRefCode,a.Amount,a.ApprovedAmount,a.Allowance_Date,a.Posted_By from hrms_employee_daily_allowance a,hrms_employee e where e.bioid=a.BioCode   and a.DALCode=?";
	public static final String GET_MANAGER = "select * from hrms_manager where ManagerCode=? and isActive='Y'";
	
	public static final String GET_DIRECTOR_EMP_ALLOWANCES = "select a.BioCode,e.First_Name,a.ProjectRefCode,a.Amount,a.ApprovedAmount,a.Allowance_Date,a.ApprovedDirectorCode,m.FirstName as mangname,a.AccountApprovedAmount from hrms_employee_daily_allowance a,hrms_employee e,hrms_manager m where e.bioid=a.BioCode and m.ManagerCode=a.Posted_By  and a.DALCode=?";
	
	public static final String GET_DIRECTOR_EMAIL_ID = "select Username from hrms_director where DirectorCode=?";
	public static final String GET_DIRECTOR_MANG_EMP_ALLOWANCES = "select a.BioCode,e.First_Name,a.ProjectRefCode,a.Amount,a.ApprovedAmount,a.Allowance_Date,a.Posted_By,m.FirstName as mangname,a.AccountApprovedAmount from hrms_employee_daily_allowance a,hrms_employee e,hrms_manager m where e.bioid=a.BioCode and m.ManagerCode=a.Posted_By  and a.DALCode=?";

}
