package com.centris.util.SQLUtils;

public class EmployeeAllowanceReportSqlUtil {

	public static final String GET_ALLOWANCES_MANAGER_WISE = " select da.Allowance_Date,da.BioCode,da.Location,da.Amount,da.No_Of_days_Month,da.Single_team_GH,da.DAType,da.ApprovedAmount,da.Project_Manager,da.ProjectRefCode,da.Remarks,substr(da.Posted_Date,1,10)as posteddate,da.Posted_By,da.ApprovedDirectorCode,da.isApprovedByDirector,substr(da.DirectorApprovedTime,1,10)as direapprovetime,da.isConflict,da.isApprovedByAccounts,da.ApprovedAccountsCode,substr(da.AccountsApprovedTime,1,10) as accntappvdate,e.First_Name as empname,c.ClientName,m.FirstName as postedbyname from hrms_employee_daily_allowance da left outer join  hrms_employee e on e.EMPID=da.EMPCODE left outer join  hrms_manager m on m.ManagerCode=da.Posted_By left outer join hrms_client c on c.ClientCode=da.ClientCode left outer join  hrms_director d on d.DirectorCode=da.ApprovedDirectorCode where da.Posted_By in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=? ) and da.Allowance_Date>=? and da.Allowance_Date<=? and  da.isApprovedByDirector like ? order by da.Posted_By,da.Allowance_Date desc";
	public static final String GET_MANAGER_NAME = "select m.FirstName as mangName,e.bioid from hrms_manager m,hrms_employee e where e.EMPID=m.EMPID  and m.isActive='Y' and m.ManagerCode=?";
	public static final String GET_DIRECTOR_NAME = "select e.First_Name as direname from hrms_employee e,hrms_director d where d.EMPID=e.EMPID and d.isActive='Y'  and d.DirectorCode=?";
	public static final String GET_ADMIN_NAME = "select e.First_Name as adminName from hrms_employee e,hrms_user u where u.empId=e.EMPID and e.isActive='Y'  and u.userCode=?";
	public static final String GET_ALLOWANCES_PROJECT_WISE = "select da.Allowance_Date,da.BioCode,da.Location,da.Amount,da.No_Of_days_Month,da.Single_team_GH,da.DAType,da.ApprovedAmount,da.Project_Manager,da.ProjectRefCode,da.Remarks,substr(da.Posted_Date,1,10)as posteddate,da.Posted_By,da.ApprovedDirectorCode,da.isApprovedByDirector,substr(da.DirectorApprovedTime,1,10)as direapprovetime, da.isConflict,da.isApprovedByAccounts,da.ApprovedAccountsCode,substr(da.AccountsApprovedTime,1,10) as accntappvdate, e.First_Name as empname,c.ClientName,m.FirstName as postedbyname,p.Project_Name from hrms_employee_daily_allowance da left outer join  hrms_employee e on e.EMPID=da.EMPCODE left outer join  hrms_manager m on m.ManagerCode=da.Posted_By left outer join hrms_client c on c.ClientCode=da.ClientCode left outer join  hrms_director d on d.DirectorCode=da.ApprovedDirectorCode left outer join  hrms_project p on p.ProjectCode=da.ProjectCode where da.Posted_By in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=? ) and da.Allowance_Date>=? and da.Allowance_Date<=? and  da.isApprovedByDirector like ? order by da.ProjectCode,da.Allowance_Date desc";
    public static final String GET_ALLOWANCES_FOR_DOWNLOAD_MANAGER_WISE="select da.Allowance_Date,da.BioCode,da.Location,da.Amount,da.No_Of_days_Month,da.Single_team_GH,da.DAType,da.ApprovedAmount,da.Project_Manager,da.ProjectRefCode,da.Remarks,substr(da.Posted_Date,1,10)as posteddate,da.Posted_By,da.ApprovedDirectorCode,da.isApprovedByDirector,substr(da.DirectorApprovedTime,1,10)as direapprovetime,da.isConflict,da.isApprovedByAccounts,da.ApprovedAccountsCode,substr(da.AccountsApprovedTime,1,10) as accntappvdate,e.First_Name as empname,c.ClientName,m.FirstName as postedbyname,da.ProjectCode,p.Project_Name from hrms_employee_daily_allowance da left outer join  hrms_employee e on e.EMPID=da.EMPCODE left outer join  hrms_manager m on m.ManagerCode=da.Posted_By left outer join hrms_client c on c.ClientCode=da.ClientCode left outer join  hrms_director d on d.DirectorCode=da.ApprovedDirectorCode left outer join  hrms_project p on p.ProjectCode=da.ProjectCode where da.Posted_By in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=? ) and da.Allowance_Date>=? and da.Allowance_Date<=? and  da.isApprovedByDirector like ? order by da.Posted_By,da.Allowance_Date desc";
	public static final String GET_ALLOWANCES_FOR_DOWNLOAD_PROJECT_WISE = "select da.Allowance_Date,da.BioCode,da.Location,da.Amount,da.No_Of_days_Month,da.Single_team_GH,da.DAType,da.ApprovedAmount,da.Project_Manager,da.ProjectRefCode,da.Remarks,substr(da.Posted_Date,1,10)as posteddate,da.Posted_By,da.ApprovedDirectorCode,da.isApprovedByDirector,substr(da.DirectorApprovedTime,1,10)as direapprovetime,da.isConflict,da.isApprovedByAccounts,da.ApprovedAccountsCode,substr(da.AccountsApprovedTime,1,10) as accntappvdate,e.First_Name as empname,c.ClientName,m.FirstName as postedbyname,da.ProjectCode,p.Project_Name from hrms_employee_daily_allowance da left outer join  hrms_employee e on e.EMPID=da.EMPCODE left outer join  hrms_manager m on m.ManagerCode=da.Posted_By left outer join hrms_client c on c.ClientCode=da.ClientCode left outer join  hrms_director d on d.DirectorCode=da.ApprovedDirectorCode left outer join  hrms_project p on p.ProjectCode=da.ProjectCode where da.Posted_By in (select ManagerCode from hrms_manager_director_mapping where DirectorCode=? ) and da.Allowance_Date>=? and da.Allowance_Date<=? and  da.isApprovedByDirector like ? order by da.ProjectCode,da.Allowance_Date desc";
	
	
	
}
