package com.centris.util.SQLUtils;

public class TravelAllowancesReportSqlUtil {

	public static final String GET_TRAVEL_ALLOWANCES_MANAGER_WISE = "select tb.Tkt_Booked_by_empcode,tb.Amount,tb.resource_who_on_travel_empcode,tb.mode,tb.Project_Manager,tb.ProjectRefCode,tb.Traveling_From,tb.Traveling_To,tb.Travelling_Date,tb.Booked_date,tb.Debit_crdit_card_usedBy_empcode,substr(tb.Posted_Date,1,10)as posteddate,tb.Posted_By,(select concat(m.FirstName,'-',ee.bioid) from hrms_employee ee  where m.ManagerCode=tb.Posted_By and ee.EMPID=m.EMPID ) as postedbyname,concat(e.First_Name,'-',e.bioid) as empname,(case when tb.DirectorApprovedTime IS NULL THEN '-'  ELSE substr(tb.DirectorApprovedTime,1,10) END)as dirappvtime,(case when tb.AccountsApprovedTime IS NULL THEN '-'  ELSE substr(tb.AccountsApprovedTime,1,10) END)as adminappvtime,(case when tb.isApprovedByDirector='Y' THEN 'Approved' ELSE 'Not Approved' END)as isappvdire,(case when tb.isApprovedByAccounts='Y' THEN 'Approved' ELSE 'Not Approved' END)as isappvaccnt,(case when tb.isConflict='Y' THEN 'Yes' ELSE 'No' END)as isconflict,(case when tb.ApprovedDirectorCode IS NULL THEN '-' ELSE (select e1.First_Name from hrms_employee e1,hrms_director d where e1.EMPID=d.EMPID and d.DirectorCode=tb.ApprovedDirectorCode) END) as dirctorname,(case when tb.ApprovedAccountsCode IS NULL THEN '-' ELSE  (select e2.First_Name from hrms_employee e2,hrms_user u where e2.EMPID=u.empId and u.userCode=tb.ApprovedAccountsCode )END) as appradminname,(case when tb.ApprovedAmount IS NULL THEN '-' ELSE tb.ApprovedAmount END)as apprvedamt from hrms_ticket_booking tb left outer join hrms_manager m on m.ManagerCode=tb.Posted_By left outer join hrms_employee e on e.EMPID=tb.Tkt_Booked_by_empcode where tb.Posted_By in(select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and isApprovedByDirector like ?  and  tb.Booked_date>=? and Booked_date<=? order by tb.Posted_By,Booked_date desc";
	public static final String GET_MANAGER_NAME = "select m.FirstName as mangName from hrms_manager m where  m.isActive='Y' and m.ManagerCode=?";
	public static final String GET_EMP_NAME = "select concat(First_Name,'-',bioid) as empName from hrms_employee where EMPID=?";
	public static final String GET_TRAVEL_ALLOWANCES_PROJECT_WISE = "select tb.Tkt_Booked_by_empcode,tb.Amount,tb.resource_who_on_travel_empcode,tb.mode,tb.Project_Manager,tb.ProjectRefCode,tb.ProjectCode,tb.Traveling_From,tb.Traveling_To,tb.Travelling_Date,tb.Booked_date,tb.Debit_crdit_card_usedBy_empcode,substr(tb.Posted_Date,1,10)as posteddate,tb.Posted_By,(select concat(m.FirstName,'-',ee.bioid) from hrms_employee ee  where m.ManagerCode=tb.Posted_By and ee.EMPID=m.EMPID ) as postedbyname,concat(e.First_Name,'-',e.bioid) as empname,concat(p.Project_Name,'  -  ',tb.ProjectRefCode)as projectname,(case when tb.DirectorApprovedTime IS NULL THEN '-'  ELSE substr(tb.DirectorApprovedTime,1,10) END)as dirappvtime,(case when tb.AccountsApprovedTime IS NULL THEN '-'  ELSE substr(tb.AccountsApprovedTime,1,10) END)as adminappvtime,(case when tb.isApprovedByDirector='Y' THEN 'Approved' ELSE 'Not Approved' END)as isappvdire,(case when tb.isApprovedByAccounts='Y' THEN 'Approved' ELSE 'Not Approved' END)as isappvaccnt,(case when tb.isConflict='Y' THEN 'Yes' ELSE 'No' END)as isconflict,(case when tb.ApprovedDirectorCode IS NULL THEN '-' ELSE (select e1.First_Name from hrms_employee e1,hrms_director d where e1.EMPID=d.EMPID and d.DirectorCode=tb.ApprovedDirectorCode) END) as dirctorname,(case when tb.ApprovedAccountsCode IS NULL THEN '-' ELSE  (select e2.First_Name from hrms_employee e2,hrms_user u where e2.EMPID=u.empId and u.userCode=tb.ApprovedAccountsCode )END) as appradminname,(case when tb.ApprovedAmount IS NULL THEN '-' ELSE tb.ApprovedAmount END)as apprvedamt from hrms_ticket_booking tb left outer join hrms_manager m on m.ManagerCode=tb.Posted_By left outer join hrms_employee e on e.EMPID=tb.Tkt_Booked_by_empcode left outer join hrms_project p on p.ProjectCode=tb.ProjectCode where tb.Posted_By in(select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and isApprovedByDirector like ? and  tb.Booked_date>=?  and Booked_date<=? order by tb.ProjectCode,Booked_date desc";
	public static final String GET_TRAVEL_ALLOWANCES_FOR_DOWNLOAD_MANAGER_WISE = "select tb.Tkt_Booked_by_empcode,tb.Amount,tb.resource_who_on_travel_empcode,tb.mode,tb.Project_Manager,tb.ProjectCode,tb.ProjectRefCode,tb.Traveling_From,tb.Traveling_To,tb.Travelling_Date,tb.Booked_date,tb.Debit_crdit_card_usedBy_empcode,substr(tb.Posted_Date,1,10)as posteddate,tb.Posted_By,(select concat(m.FirstName,'-',ee.bioid) from hrms_employee ee  where m.ManagerCode=tb.Posted_By and ee.EMPID=m.EMPID ) as postedbyname,concat(e.First_Name,'-',e.bioid) as empname,concat(p.Project_Name,'  -  ',tb.ProjectRefCode)as projectname,(case when tb.DirectorApprovedTime IS NULL THEN '-'  ELSE substr(tb.DirectorApprovedTime,1,10) END)as dirappvtime,(case when tb.AccountsApprovedTime IS NULL THEN '-'  ELSE substr(tb.AccountsApprovedTime,1,10) END)as adminappvtime,(case when tb.isApprovedByDirector='Y' THEN 'Approved' ELSE 'Not Approved' END)as isappvdire,(case when tb.isApprovedByAccounts='Y' THEN 'Approved' ELSE 'Not Approved' END)as isappvaccnt,(case when tb.isConflict='Y' THEN 'Yes' ELSE 'No' END)as isconflict,(case when tb.ApprovedDirectorCode IS NULL THEN '-' ELSE (select e1.First_Name from hrms_employee e1,hrms_director d where e1.EMPID=d.EMPID and d.DirectorCode=tb.ApprovedDirectorCode) END) as dirctorname,(case when tb.ApprovedAccountsCode IS NULL THEN '-' ELSE  (select e2.First_Name from hrms_employee e2,hrms_user u where e2.EMPID=u.empId and u.userCode=tb.ApprovedAccountsCode )END) as appradminname,(case when tb.ApprovedAmount IS NULL THEN '-' ELSE tb.ApprovedAmount END)as apprvedamt from hrms_ticket_booking tb left outer join hrms_manager m on m.ManagerCode=tb.Posted_By left outer join hrms_employee e on e.EMPID=tb.Tkt_Booked_by_empcode left outer join hrms_project p on p.ProjectCode=tb.ProjectCode where tb.Posted_By in(select ManagerCode from hrms_manager_director_mapping where DirectorCode=?) and isApprovedByDirector like ? and  tb.Booked_date>=?  and Booked_date<=? order by tb.Posted_By,Booked_date desc";
	

}
